import { relations } from "drizzle-orm";
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { randomUUID } from "crypto";

// Re-export auth models (users and sessions tables)
export * from "./models/auth";
// Re-export chat models (conversations and messages tables)
export * from "./models/chat";

// Enums - SQLite doesn't have native enums, so we use text with check constraints
// For simplicity, we'll just use text fields and validate in the application layer

// User roles - extends the auth users table
export const userProfiles = sqliteTable("user_profiles", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  userId: text("user_id").notNull(),
  role: text("role", { enum: ["admin", "student", "tutor"] }).default("student").notNull(),
  levelId: text("level_id"),
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
});

// Import users from auth for foreign key references
import { users } from "./models/auth";

// Levels (7° Básico, 8° Básico, etc.)
export const levels = sqliteTable("levels", {
  id: text("id").primaryKey(), // e.g., "7b", "8b", "1m", etc.
  name: text("name").notNull(), // "7° Básico"
  programType: text("program_type", { enum: ["menores", "adultos"] }).notNull(),
  totalWeeks: integer("total_weeks").default(30).notNull(),
  cadencePerOA: text("cadence_per_oa"), // "2.18 sem/OA"
  sortOrder: integer("sort_order").default(0).notNull(),
});

// Subjects (Matemáticas, Lenguaje, etc.)
export const subjects = sqliteTable("subjects", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
});

// Level-Subject association (which subjects are in which levels)
export const levelSubjects = sqliteTable("level_subjects", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  levelId: text("level_id").notNull().references(() => levels.id),
  subjectId: text("subject_id").notNull().references(() => subjects.id),
  totalOAs: integer("total_oas").default(0),
  textbookPdfUrl: text("textbook_pdf_url"),
  textbookTitle: text("textbook_title"),
});

// Learning Objectives (OAs - Objetivos de Aprendizaje) / Módulos
export const learningObjectives = sqliteTable("learning_objectives", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  levelSubjectId: text("level_subject_id").notNull().references(() => levelSubjects.id),
  code: text("code").notNull(), // "OA 3"
  title: text("title").notNull(),
  description: text("description"),
  weekNumber: integer("week_number").notNull(), // Actually module number (1-15)
  sortOrder: integer("sort_order").default(0).notNull(),
  textbookStartPage: integer("textbook_start_page"),
  textbookEndPage: integer("textbook_end_page"),
  moduleOAs: text("module_oas"), // OAs del módulo extraídos del Word
  moduleContents: text("module_contents"), // Contenidos del módulo extraídos del Word
  moduleDateRange: text("module_date_range"), // Rango de fechas del módulo
  wordDocUrl: text("word_doc_url"), // URL del documento Word original
});

// Program Calendar Configuration
export const programCalendar = sqliteTable("program_calendar", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  levelId: text("level_id").notNull().references(() => levels.id),
  startDate: integer("start_date", { mode: "timestamp" }).notNull(), // March 9, 2026
  moduleDurationWeeks: integer("module_duration_weeks").default(2).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
});

// Module Evaluations (4 per module - Wed/Fri for 2 weeks)
export const moduleEvaluations = sqliteTable("module_evaluations", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  learningObjectiveId: text("learning_objective_id").notNull().references(() => learningObjectives.id),
  evaluationNumber: integer("evaluation_number").notNull(), // 1, 2, 3, or 4
  title: text("title").notNull(),
  description: text("description"),
  releaseDay: integer("release_day").default(5).notNull(), // Day of week (3 = Wed, 5 = Fri)
  releaseWeek: integer("release_week").notNull(), // 1 or 2 (which week of the module)
  formUrl: text("form_url"), // Google Form URL (legacy)
  htmlContent: text("html_content"), // Gemini-generated HTML content
  questionsJson: text("questions_json"), // JSON array of AI-generated questions
  totalQuestions: integer("total_questions"), // Number of questions (15 or 20)
  passingScore: integer("passing_score").default(60), // Passing percentage (60%)
  generatedAt: integer("generated_at", { mode: "timestamp" }), // When questions were generated by AI
  isRequired: integer("is_required", { mode: "boolean" }).default(true),
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
});

// Student Evaluation Progress
export const evaluationProgress = sqliteTable("evaluation_progress", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  userId: text("user_id").notNull().references(() => users.id),
  evaluationId: text("evaluation_id").notNull().references(() => moduleEvaluations.id),
  completedAt: integer("completed_at", { mode: "timestamp" }),
  score: integer("score"),
  totalCorrect: integer("total_correct"), // Number of correct answers
  totalQuestions: integer("total_questions"), // Total questions answered
  answersJson: text("answers_json"), // JSON array of user's answers
  passed: integer("passed", { mode: "boolean" }).default(false),
});

// Weekly Resources (7 tipos por semana)
export const weeklyResources = sqliteTable("weekly_resources", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  learningObjectiveId: text("learning_objective_id").notNull().references(() => learningObjectives.id),
  resourceType: text("resource_type", { enum: ["video", "infografia", "audio", "presentacion"] }).notNull(),
  title: text("title").notNull(),
  notebookLmUrl: text("notebook_lm_url"),
  barkleyFoundation: text("barkley_foundation"), // "Activación Atencional (Barkley)"
  studentHelp: text("student_help"), // "Voz al alumno" text
  pedagogicalObjective: text("pedagogical_objective"),
  sortOrder: integer("sort_order").default(0).notNull(),
  isActive: integer("is_active", { mode: "boolean" }).default(true),
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).defaultNow(),
});

// Student Enrollments
export const enrollments = sqliteTable("enrollments", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  userId: text("user_id").notNull().references(() => users.id),
  levelSubjectId: text("level_subject_id").notNull().references(() => levelSubjects.id),
  enrolledAt: integer("enrolled_at", { mode: "timestamp" }).defaultNow(),
  isActive: integer("is_active", { mode: "boolean" }).default(true),
});

// Student Progress (tracks which resources have been completed)
export const studentProgress = sqliteTable("student_progress", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  userId: text("user_id").notNull().references(() => users.id),
  resourceId: text("resource_id").notNull().references(() => weeklyResources.id),
  completedAt: integer("completed_at", { mode: "timestamp" }).defaultNow(),
  score: integer("score"), // For cuestionario
});

// Weekly completion status
export const weeklyCompletion = sqliteTable("weekly_completion", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  userId: text("user_id").notNull().references(() => users.id),
  learningObjectiveId: text("learning_objective_id").notNull().references(() => learningObjectives.id),
  isComplete: integer("is_complete", { mode: "boolean" }).default(false),
  completedAt: integer("completed_at", { mode: "timestamp" }),
  examScore: integer("exam_score"),
});

// Relations
export const levelsRelations = relations(levels, ({ many }) => ({
  levelSubjects: many(levelSubjects),
}));

export const subjectsRelations = relations(subjects, ({ many }) => ({
  levelSubjects: many(levelSubjects),
}));

export const levelSubjectsRelations = relations(levelSubjects, ({ one, many }) => ({
  level: one(levels, {
    fields: [levelSubjects.levelId],
    references: [levels.id],
  }),
  subject: one(subjects, {
    fields: [levelSubjects.subjectId],
    references: [subjects.id],
  }),
  learningObjectives: many(learningObjectives),
}));

export const learningObjectivesRelations = relations(learningObjectives, ({ one, many }) => ({
  levelSubject: one(levelSubjects, {
    fields: [learningObjectives.levelSubjectId],
    references: [levelSubjects.id],
  }),
  resources: many(weeklyResources),
  evaluations: many(moduleEvaluations),
}));

export const programCalendarRelations = relations(programCalendar, ({ one }) => ({
  level: one(levels, {
    fields: [programCalendar.levelId],
    references: [levels.id],
  }),
}));

export const moduleEvaluationsRelations = relations(moduleEvaluations, ({ one, many }) => ({
  learningObjective: one(learningObjectives, {
    fields: [moduleEvaluations.learningObjectiveId],
    references: [learningObjectives.id],
  }),
  progress: many(evaluationProgress),
}));

export const evaluationProgressRelations = relations(evaluationProgress, ({ one }) => ({
  user: one(users, {
    fields: [evaluationProgress.userId],
    references: [users.id],
  }),
  evaluation: one(moduleEvaluations, {
    fields: [evaluationProgress.evaluationId],
    references: [moduleEvaluations.id],
  }),
}));

export const weeklyResourcesRelations = relations(weeklyResources, ({ one }) => ({
  learningObjective: one(learningObjectives, {
    fields: [weeklyResources.learningObjectiveId],
    references: [learningObjectives.id],
  }),
}));

// Insert schemas
export const insertLevelSchema = createInsertSchema(levels);
export const insertSubjectSchema = createInsertSchema(subjects).omit({ id: true, createdAt: true });
export const insertLevelSubjectSchema = createInsertSchema(levelSubjects).omit({ id: true });
export const insertLearningObjectiveSchema = createInsertSchema(learningObjectives).omit({ id: true });
export const insertWeeklyResourceSchema = createInsertSchema(weeklyResources).omit({ id: true, createdAt: true, updatedAt: true });
export const insertEnrollmentSchema = createInsertSchema(enrollments).omit({ id: true, enrolledAt: true });
export const insertStudentProgressSchema = createInsertSchema(studentProgress).omit({ id: true, completedAt: true });
export const insertUserProfileSchema = createInsertSchema(userProfiles).omit({ id: true, createdAt: true });
export const insertProgramCalendarSchema = createInsertSchema(programCalendar).omit({ id: true, createdAt: true });
export const insertModuleEvaluationSchema = createInsertSchema(moduleEvaluations).omit({ id: true, createdAt: true });
export const insertEvaluationProgressSchema = createInsertSchema(evaluationProgress).omit({ id: true });

const baseLevelSubjectTextbookSchema = createInsertSchema(levelSubjects, {
  textbookPdfUrl: z.preprocess(
    (val) => (val === '' ? null : val),
    z.string().url({ message: 'Invalid URL format' }).nullable().optional()
  ),
  textbookTitle: z.preprocess(
    (val) => (val === '' ? null : val),
    z.string().nullable().optional()
  )
}).pick({
  textbookPdfUrl: true,
  textbookTitle: true
}).partial();

export const updateLevelSubjectTextbookSchema = baseLevelSubjectTextbookSchema;

const baseLearningObjectivePagesSchema = createInsertSchema(learningObjectives, {
  textbookStartPage: z.preprocess(
    (val) => {
      if (val === '' || val === null) return null;
      if (val === undefined) return undefined;
      if (typeof val === 'string') return parseInt(val, 10);
      return val;
    },
    z.number({ invalid_type_error: 'Must be a number' })
      .int({ message: 'Must be an integer' })
      .min(1, { message: 'Must be at least 1' })
      .nullable()
      .optional()
  ),
  textbookEndPage: z.preprocess(
    (val) => {
      if (val === '' || val === null) return null;
      if (val === undefined) return undefined;
      if (typeof val === 'string') return parseInt(val, 10);
      return val;
    },
    z.number({ invalid_type_error: 'Must be a number' })
      .int({ message: 'Must be an integer' })
      .min(1, { message: 'Must be at least 1' })
      .nullable()
      .optional()
  )
}).pick({
  textbookStartPage: true,
  textbookEndPage: true
}).partial();

export const updateLearningObjectivePagesSchema = baseLearningObjectivePagesSchema;

// Types
export type Level = typeof levels.$inferSelect;
export type InsertLevel = z.infer<typeof insertLevelSchema>;
export type Subject = typeof subjects.$inferSelect;
export type InsertSubject = z.infer<typeof insertSubjectSchema>;
export type LevelSubject = typeof levelSubjects.$inferSelect;
export type InsertLevelSubject = z.infer<typeof insertLevelSubjectSchema>;
export type LearningObjective = typeof learningObjectives.$inferSelect;
export type InsertLearningObjective = z.infer<typeof insertLearningObjectiveSchema>;
export type WeeklyResource = typeof weeklyResources.$inferSelect;
export type InsertWeeklyResource = z.infer<typeof insertWeeklyResourceSchema>;
export type Enrollment = typeof enrollments.$inferSelect;
export type InsertEnrollment = z.infer<typeof insertEnrollmentSchema>;
export type StudentProgress = typeof studentProgress.$inferSelect;
export type InsertStudentProgress = z.infer<typeof insertStudentProgressSchema>;
export type UserProfile = typeof userProfiles.$inferSelect;
export type InsertUserProfile = z.infer<typeof insertUserProfileSchema>;
export type ProgramCalendar = typeof programCalendar.$inferSelect;
export type InsertProgramCalendar = z.infer<typeof insertProgramCalendarSchema>;
export type ModuleEvaluation = typeof moduleEvaluations.$inferSelect;
export type InsertModuleEvaluation = z.infer<typeof insertModuleEvaluationSchema>;
export type EvaluationProgress = typeof evaluationProgress.$inferSelect;
export type InsertEvaluationProgress = z.infer<typeof insertEvaluationProgressSchema>;

// Textbook configurations - PDF page mappings per module
export const textbookConfigs = sqliteTable("textbook_configs", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  subjectId: text("subject_id").notNull().references(() => subjects.id),
  driveFolderId: text("drive_folder_id"), // Google Drive folder ID containing PDFs
  pdfUrl: text("pdf_url"), // Legacy: Single PDF URL (optional)
  pdfName: text("pdf_name").notNull(),
  totalPages: integer("total_pages"),
  // JSON object: { "module_1": { "start": 1, "end": 15, "pdfUrl": "..." }, "module_2": { "start": 16, "end": 30, "pdfUrl": "..." } }
  modulePagesConfig: text("module_pages_config").notNull().default("{}"),
  // JSON object: Stores the auto-matched PDFs { "module_1": { "pdfUrl": "...", "fileName": "..." } }
  modulePDFsMap: text("module_pdfs_map").default("{}"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const textbookConfigsRelations = relations(textbookConfigs, ({ one }) => ({
  subject: one(subjects, {
    fields: [textbookConfigs.subjectId],
    references: [subjects.id],
  }),
}));

export const insertTextbookConfigSchema = createInsertSchema(textbookConfigs, {
  driveFolderId: z.string().optional(),
  pdfUrl: z.string().optional(),
  pdfName: z.string().min(1),
  modulePagesConfig: z.string().default("{}"),
  modulePDFsMap: z.string().default("{}"),
});

export type TextbookConfig = typeof textbookConfigs.$inferSelect;
export type InsertTextbookConfig = z.infer<typeof insertTextbookConfigSchema>;

// Reservations - Formulario de Reserva de Cupo
export const reservations = sqliteTable("reservations", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  // Datos personales
  fullName: text("full_name").notNull(),
  rut: text("rut").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  dateOfBirth: text("date_of_birth").notNull(),
  
  // Datos del programa
  programType: text("program_type", { enum: ["focus", "impulso", "stratmore", "tutoria"] }).notNull(),
  levelInterest: text("level_interest"), // 7°B, 8°B, 1°M, etc.
  
  // Datos adicionales (eliminados del formulario pero mantenidos en DB por compatibilidad)
  howDidYouHear: text("how_did_you_hear"),
  comments: text("comments"),
  
  // Metadata
  status: text("status", { enum: ["pending", "contacted", "enrolled", "rejected"] }).default("pending").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).defaultNow(),
});

// Schema base sin validación de Gmail personalizada
const baseReservationSchema = createInsertSchema(reservations).omit({ 
  id: true, 
  status: true, 
  createdAt: true, 
  updatedAt: true 
});

// Schema para el formulario con validación de Gmail
export const insertReservationSchema = z.object({
  fullName: z.string().min(2, "El nombre debe tener al menos 2 caracteres"),
  rut: z.string().min(8, "RUT inválido"),
  email: z.string().email("Email inválido").refine(
    (email) => email.endsWith("@gmail.com"),
    { message: "Debe usar una cuenta de Gmail (@gmail.com)" }
  ),
  phone: z.string().min(8, "Teléfono inválido"),
  dateOfBirth: z.string(),
  programType: z.enum(["focus", "impulso", "stratmore", "tutoria"]),
  levelInterest: z.string().optional(),
  howDidYouHear: z.string().optional(),
  comments: z.string().optional(),
});

export type Reservation = typeof reservations.$inferSelect;
export type InsertReservation = z.infer<typeof insertReservationSchema>;

// Barkley Institute Plans Configuration - OLD (mantener por compatibilidad)
export const planConfigurations = sqliteTable("plan_configurations", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  planKey: text("plan_key").notNull().unique(),
  planName: text("plan_name").notNull(),
  planSubtitle: text("plan_subtitle"),
  monthlyPrice: integer("monthly_price").notNull(),
  enrollmentPrice: integer("enrollment_price").notNull(),
  annualTotal: integer("annual_total"),
  academicLoad: text("academic_load"),
  evaluationsDetail: text("evaluations_detail"),
  subjects: text("subjects").notNull().default('["Lenguaje","Matemática","Historia","Ciencias","Inglés"]'),
  description: text("description"),
  category: text("category"),
  linkText: text("link_text"),
  isActive: integer("is_active", { mode: "boolean" }).default(true).notNull(),
  sortOrder: integer("sort_order").default(0).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).defaultNow(),
});

export const insertPlanConfigurationSchema = createInsertSchema(planConfigurations, {
  planKey: z.string().min(1, "La clave del plan es requerida"),
  planName: z.string().min(2, "El nombre del plan es requerido"),
  monthlyPrice: z.number().int().min(0, "El precio mensual debe ser positivo"),
  enrollmentPrice: z.number().int().min(0, "El precio de matrícula debe ser positivo"),
  subjects: z.string().default('["Lenguaje","Matemática","Historia","Ciencias","Inglés"]'),
}).omit({ id: true, createdAt: true, updatedAt: true });

export type PlanConfiguration = typeof planConfigurations.$inferSelect;
export type InsertPlanConfiguration = z.infer<typeof insertPlanConfigurationSchema>;

// ============================================
// Level-Based Plan Configurations - NEW SYSTEM
// Organizado por NIVEL, no por PLAN
// ============================================

export const levelPlanConfigurations = sqliteTable("level_plan_configurations", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  
  // Level Group Identification
  levelGroupKey: text("level_group_key").notNull().unique(), // "7b-2m_menores", "3m-4m_menores", "adultos"
  levelGroupName: text("level_group_name").notNull(), // "7° Básico a 2° Medio"
  programType: text("program_type", { enum: ["menores", "adultos"] }).notNull(), // "menores" o "adultos"
  levelsIncluded: text("levels_included").notNull(), // JSON array: ["7b", "8b", "1m", "2m"]
  
  // Pricing for this level group
  monthlyPriceFull: integer("monthly_price_full").notNull(), // Plan Full
  monthlyPriceStandard: integer("monthly_price_standard").notNull(), // Plan Estándar
  monthlyPriceTutor: integer("monthly_price_tutor").notNull(), // Solo Tutor
  enrollmentPrice: integer("enrollment_price").notNull(), // Matrícula común
  
  // Academic Details
  modules: integer("modules").default(15).notNull(), // 15 módulos
  evaluationsPerModule: integer("evaluations_per_module").default(4).notNull(), // 4 evaluaciones por módulo
  totalEvaluations: integer("total_evaluations").default(60).notNull(), // 60 evaluaciones anuales
  essays: integer("essays").default(2).notNull(), // 2 ensayos Mineduc
  sessionsPerMonth: integer("sessions_per_month").default(2), // 2 sesiones mensuales (Full/Tutor)
  
  // Subjects (JSON array) - Específico por nivel
  subjects: text("subjects").notNull().default('["Lenguaje","Matemática","Ciencias Naturales","Historia y Geografía","Inglés"]'),
  
  // Display Settings
  isActive: integer("is_active", { mode: "boolean" }).default(true).notNull(),
  sortOrder: integer("sort_order").default(0).notNull(),
  
  // Metadata
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).defaultNow(),
});

export const insertLevelPlanConfigurationSchema = createInsertSchema(levelPlanConfigurations, {
  levelGroupKey: z.string().min(1, "La clave del grupo es requerida"),
  levelGroupName: z.string().min(2, "El nombre del grupo es requerido"),
  programType: z.enum(["menores", "adultos"]),
  levelsIncluded: z.string().min(1, "Debe incluir al menos un nivel"),
  monthlyPriceFull: z.number().int().min(0, "El precio debe ser positivo"),
  monthlyPriceStandard: z.number().int().min(0, "El precio debe ser positivo"),
  monthlyPriceTutor: z.number().int().min(0, "El precio debe ser positivo"),
  enrollmentPrice: z.number().int().min(0, "El precio de matrícula debe ser positivo"),
  subjects: z.string().min(1, "Debe incluir asignaturas"),
}).omit({ id: true, createdAt: true, updatedAt: true });

export type LevelPlanConfiguration = typeof levelPlanConfigurations.$inferSelect;
export type InsertLevelPlanConfiguration = z.infer<typeof insertLevelPlanConfigurationSchema>;

// Site Configuration - General settings for the landing page
export const siteConfiguration = sqliteTable("site_configuration", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  configKey: text("config_key").notNull().unique(), // "header_description", "important_notice", etc.
  configValue: text("config_value").notNull(),
  configType: text("config_type").default("text").notNull(), // "text", "html", "json"
  description: text("description"),
  updatedAt: integer("updated_at", { mode: "timestamp" }).defaultNow(),
});

// Adult Education Cycles Configuration
export const adultCycleConfigurations = sqliteTable("adult_cycle_configurations", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  
  cycleKey: text("cycle_key").notNull().unique(), // "cycle_1_june", "cycle_2_october"
  cycleName: text("cycle_name").notNull(), // "Ciclo 1 (Junio)"
  
  // Pricing
  monthlyPrice: integer("monthly_price").notNull(), // 45000
  enrollmentPrice: integer("enrollment_price").notNull(), // 15000
  totalPrice: integer("total_price").notNull(), // 195000
  durationMonths: integer("duration_months").notNull(), // 4 or 8
  
  // Academic Details
  modulesCount: integer("modules_count").notNull(), // 6 or 15
  quizzesTotal: integer("quizzes_total").notNull(), // 24 or 60
  essaysCount: integer("essays_count").notNull(), // 1 or 2
  academicLoad: text("academic_load"), // "6 Módulos, 24 Quizzes Totales y 1 Ensayo General Final"
  
  // Subjects by decree
  basicaDS10: text("basica_ds10"), // JSON array for D.S. 10
  basicaDS257: text("basica_ds257"), // JSON array for D.S. 257
  mediaDS257: text("media_ds257"), // JSON array for D.S. 257
  
  // Display
  isActive: integer("is_active", { mode: "boolean" }).default(true).notNull(),
  sortOrder: integer("sort_order").default(0).notNull(),
  
  updatedAt: integer("updated_at", { mode: "timestamp" }).defaultNow(),
});

export const insertSiteConfigurationSchema = createInsertSchema(siteConfiguration).omit({ 
  id: true, 
  updatedAt: true 
});

export const insertAdultCycleConfigurationSchema = createInsertSchema(adultCycleConfigurations, {
  cycleKey: z.string().min(1, "La clave del ciclo es requerida"),
  cycleName: z.string().min(2, "El nombre del ciclo es requerido"),
  monthlyPrice: z.number().int().min(0, "El precio mensual debe ser positivo"),
  enrollmentPrice: z.number().int().min(0, "El precio de matrícula debe ser positivo"),
  totalPrice: z.number().int().min(0, "El total debe ser positivo"),
  durationMonths: z.number().int().min(1, "La duración debe ser al menos 1 mes"),
  modulesCount: z.number().int().min(1, "Debe haber al menos 1 módulo"),
  quizzesTotal: z.number().int().min(1, "Debe haber al menos 1 quiz"),
  essaysCount: z.number().int().min(0, "Los ensayos no pueden ser negativos"),
}).omit({ id: true, updatedAt: true });

export type SiteConfiguration = typeof siteConfiguration.$inferSelect;
export type InsertSiteConfiguration = z.infer<typeof insertSiteConfigurationSchema>;
export type AdultCycleConfiguration = typeof adultCycleConfigurations.$inferSelect;
export type InsertAdultCycleConfiguration = z.infer<typeof insertAdultCycleConfigurationSchema>;

// ============================================
// Evaluation Links (Gemini) - SQLite version
// ============================================

export const evaluationLinks = sqliteTable("evaluation_links", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  courseId: text("course_id").notNull(), // Using text to match levelSubject IDs
  moduleNumber: integer("module_number").notNull(),
  evaluationNumber: integer("evaluation_number").notNull(), // 1, 2, 3, or 4
  geminiLink: text("gemini_link").notNull(),
  title: text("title"),
  releaseDate: integer("release_date", { mode: "timestamp" }), // Fecha calculada de liberación
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).defaultNow(),
});

export const insertEvaluationLinkSchema = createInsertSchema(evaluationLinks, {
  courseId: z.string().min(1, "El ID del curso es requerido"),
  moduleNumber: z.number().int().min(1, "El número de módulo debe ser al menos 1"),
  evaluationNumber: z.number().int().min(1).max(4, "El número de evaluación debe ser entre 1 y 4"),
  geminiLink: z.string().url("Debe ser una URL válida"),
  title: z.string().optional(),
  releaseDate: z.date().optional(),
}).omit({ id: true, createdAt: true, updatedAt: true });

export type EvaluationLink = typeof evaluationLinks.$inferSelect;
export type InsertEvaluationLink = z.infer<typeof insertEvaluationLinkSchema>;

// ============================================
// Gemini Copilots - AI Assistants per course groups
// ============================================

export const geminiCopilots = sqliteTable("gemini_copilots", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  name: text("name").notNull(), // "Academic Copilot I"
  geminiLink: text("gemini_link").notNull(), // Link to Gemini copilot
  description: text("description"), // Optional description
  // JSON array of level IDs this copilot serves: ["3m", "4m"]
  levelIds: text("level_ids").notNull().default("[]"),
  isActive: integer("is_active", { mode: "boolean" }).default(true),
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).defaultNow(),
});

export const insertGeminiCopilotSchema = createInsertSchema(geminiCopilots, {
  name: z.string().min(1, "El nombre es requerido"),
  geminiLink: z.string().url("Debe ser una URL válida"),
  description: z.string().optional(),
  levelIds: z.string().default("[]"),
  isActive: z.boolean().optional().default(true),
}).omit({ id: true, createdAt: true, updatedAt: true });

export type GeminiCopilot = typeof geminiCopilots.$inferSelect;
export type InsertGeminiCopilot = z.infer<typeof insertGeminiCopilotSchema>;

// ============================================
// FAQ - Frequently Asked Questions
// ============================================

export const faqs = sqliteTable("faqs", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  question: text("question").notNull(),
  answer: text("answer").notNull(),
  category: text("category"), // Optional: "planes", "academico", "certificacion", etc.
  sortOrder: integer("sort_order").default(0).notNull(),
  isActive: integer("is_active", { mode: "boolean" }).default(true).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).defaultNow(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).defaultNow(),
});

export const insertFaqSchema = createInsertSchema(faqs, {
  question: z.string().min(5, "La pregunta debe tener al menos 5 caracteres"),
  answer: z.string().min(10, "La respuesta debe tener al menos 10 caracteres"),
  category: z.string().optional(),
  sortOrder: z.number().int().min(0).optional().default(0),
  isActive: z.boolean().optional().default(true),
}).omit({ id: true, createdAt: true, updatedAt: true });

export type Faq = typeof faqs.$inferSelect;
export type InsertFaq = z.infer<typeof insertFaqSchema>;
